name: Auto Push Billing Index

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "chatgpt-auto-bot"
          git config user.email "bot@chatgpt.local"

      - name: Commit index.html
        run: |
          git add index.html
          git commit -m "Auto-update index.html from ChatGPT" || echo "No changes to commit"
          git push origin main
